name = "aitorsanchez-blog"
compatibility_date = "2024-04-03"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "mi-blog-db"
database_id = "b3d646b0-076f-48e5-9101-4cf934b91374"
