backend:
  name: github
  repo: spankyno/mi-blog
  branch: main
  base_url: https://aitorsanchez-oauth.asanchezgu.workers.dev
  auth_type: implicit
  app_id: tu_client_id_de_github

media_folder: public/images
public_folder: /images

collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: title, widget: string }
      - { label: "Descripción", name: description, widget: string }
      - { label: "Fecha", name: pubDate, widget: datetime, format: "YYYY-MM-DD" }
      - { label: "Imagen destacada", name: heroImage, widget: image, required: false }
      - { label: "Tags", name: tags, widget: list, default: [] }
      - { label: "Borrador", name: draft, widget: boolean, default: false }
      - { label: "Contenido", name: body, widget: markdown }

  - name: portfolio
    label: Portfolio
    folder: src/content/portfolio
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: title, widget: string }
      - { label: "Descripción", name: description, widget: string }
      - { label: "Fecha", name: pubDate, widget: datetime, format: "YYYY-MM-DD" }
      - { label: "Imagen", name: image, widget: image, required: false }
      - { label: "URL del proyecto", name: url, widget: string, required: false }
      - { label: "Tags", name: tags, widget: list, default: [] }
      - { label: "Contenido", name: body, widget: markdown }
